export { analyze } from './analyze'
export type { AnalyzeResult } from './analyze'
export { buildRows, splitKeywordsAndTerms } from './buildRows'
export { detectColumns, REQUIRED_ROLES, ROLES } from './columnDetect'
export type { RoleDescriptor } from './columnDetect'
export { comparePeriods } from './compare'
export type { CampaignDelta, CompareResult, Trend } from './compare'
export { ingestCsv } from './csvIngest'
export type { CsvIngestFailure, CsvIngestResult, CsvIngestSuccess } from './csvIngest'
export { average, computeMetrics, groupBy } from './metrics'
export { ngramReport } from './ngrams'
export type { NgramReportOptions, NgramStat } from './ngrams'
export { parseNumberPtBrOrEn } from './numberParse'
export { cpaRule } from './rules/cpa'
export { goalGapRule } from './rules/goalGap'
export { groupsRule } from './rules/groups'
export { volumeRule } from './rules/volume'
export { wasteRule, wasteSummary } from './rules/waste'
export { DEFAULT_ENGINE_PARAMS } from './types'
export type { AdsRow, EngineParams, GoalTargets, Metrics } from './types'
